name: Bleeding Edge Build
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Build Project
      run: msbuild SchoolWallpaperChanger.sln /t:Build /p:Configuration=Debug
    - name: Resolve Short Commit Hash
      if: startsWith(github.ref, 'refs/tags/') == false
      id: get_hash
      shell: bash
      run: echo "hash=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT
    - name: Upload Debug Build
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v3.1.1
      with:
        name: SchoolWallpaperChanger-${{ steps.get_hash.outputs.hash }}
        path: ./bin/x64/Debug/
